before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libsdl1.2-dev
  - sudo apt-get install libsdl-gfx1.2-dev
  - git clone https://github.com/brson/rust-sdl.git
  - export RUST_PATH=$(pwd)/rust-sdl
  - rustpkg install sdl
script:
  - rustpkg build gfx # for example, using rustpkg not required
